### ISSUE TITLE
Coraz gorzej

### ISSUE THREAD

**Issue by p0k33m0n** [CrusheerPL/AlleBlockV2#2]
1) laczenie podobnych przedmiotow - nie dziala
2) obserwowane wyszukiwania - nie dziala

Itd. Zle to wyglada.

**Comment by CrusheerPL** [comment]
Sprawdzę to, jak znajdzie się więcej takich smaczków dawaj znać

**Comment by CrusheerPL** [comment]
co do tego pierwszego, zostało to poprawione, jeśli chodzi o drugie to nie wiem, jakiś inny zestaw reguł musiał to popsuć, u mnie wszystko jest w porządku
![obraz](https://github.com/CrusheerPL/AlleBlockV2/assets/35576727/7c7c75f0-0bec-404d-9f86-571971de81e7)

**Comment by p0k33m0n** [comment]
Bardzo, bardzo dziekuje. Nie spodziewalem sie tak szybkiej reakcji, wlasciwie nie spodziewalem sie zadnej rekacji. Super robota! Wszystko dziala. Co do "wyszukiwanie w ulubionych" wystarczylo pobrac najnowsza wersje filtra i blad tez zniknal. Tak wiec na ten moment wszystko bez zarzutu. Jak cos jeszcze znajde bede dawac znac. Jeszcze raz doceniam wlozona prace: Allegro to w tej chwili SPAMowy smietnik, tego serwisu po prostu nie da sie przegladac bez blockera reklam - sa obecnie duuuzo gorsi od Amazonu w tym temacie przypominajac bardziej chinski AliExpress, niz europejskie standardy.
