### ISSUE TITLE
Parametry i Opis

### ISSUE THREAD

**Issue by p0k33m0n** [CrusheerPL/AlleBlockV2#3]
Czesc, 

Filtr zaczal wycinac Parametry i Opis w aukcjach, pozostaly tylko Opinie o produkcie.

**Comment by CrusheerPL** [comment]
Znalazłem przyczynę - zmieniła się nieco struktura strony (celowa zagrywka czy jednak to niepowiązane z tą listą - na to już każdy musi sobie sam odpowiedzieć), za chwilę powinno być to poprawione

**Comment by p0k33m0n** [comment]
Ponownie dziekuje!
